name: helm-uninstall-action
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - '**'
jobs:
  test:
    steps:
    - name: write kube config
      uses: docker://alpine:3.17
      shell: sh
      run: |
        mkdir -p ${HOME}/.kube
        echo -e "${{ secrets.STAGING_CONFIG }}" > ${HOME}/.kube/config
    - name: checkout
      uses: cloudbees-io/checkout@v1
    - id: createns
      name: Create Kubernetes Namespace
      uses: cloudbees-io/create-k8s-namespace@v1
      with:
        name: ${{ format('{0}{1}{2}', cloudbees.scm.branch, cloudbees.scm.repository, cloudbees.scm.sha) }}
        sanitize-name: "true"
        labels: |
          cloudbees.io/cleanup: "true"
    - name: install a helm chart
      uses: cloudbees-io/helm-install@v1
      with:
        release-name: nginx-example
        chart-location: oci://registry-1.docker.io/bitnamicharts/nginx
        version: 15.4.2
        namespace: ${{ steps.createns.outputs.name }}
        timeout: 1m
        values: |
          service:
            type: ClusterIP
    - name: uninstall a helm chart with dry-run
      uses: .
      with:
        release-name: nginx-example
        namespace: ${{ steps.createns.outputs.name }}
        timeout: 1m
        dry-run: "true"
    - name: uninstall a helm chart
      uses: .
      with:
        release-name: nginx-example
        namespace: ${{ steps.createns.outputs.name }}
        timeout: 1m
  build:
    steps:
    - name: get source code
      uses: cloudbees-io/checkout@v1
    - id: dockerconfig
      name: Configure container registry credentials
      uses: cloudbees-io/configure-oci-credentials@v0
      with:
        registry: ${{ vars.STAGING_DOCKER_REGISTRY }}
        username: ${{ secrets.STAGING_DOCKER_USERNAME }}
        password: ${{ secrets.STAGING_DOCKER_PASSWORD }}
    - name: docker build and publish
      uses: cloudbees-io/kaniko@v1
      with:
        destination: registry.saas-dev.beescloud.com/staging/helm-uninstall-action:${{ cloudbees.scm.sha }}${{ cloudbees.scm.branch == 'main' && ',registry.saas-dev.beescloud.com/staging/helm-uninstall-action:1.0.1,registry.saas-dev.beescloud.com/staging/helm-install-action:latest' || '' }}
        labels: maintaner=sdp-pod-3,email=engineering@cloudbees.io
